# Generated by Django 3.2.15 on 2022-09-16 14:28

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='student',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30)),
                ('rollnum', models.CharField(max_length=30)),
                ('age', models.IntegerField()),
                ('mobile', models.CharField(max_length=30)),
                ('email', models.EmailField(max_length=30)),
                ('address', models.TextField()),
            ],
        ),
    ]
